const $ = s => document.querySelector(s);
const visual=$('#visual'), caption=$('#caption'), timeInput=$('#time');
const groups=['core','wings','ring','shards'];
const params=new URLSearchParams(location.search);
if(params.has('overlay'))document.body.classList.add('overlay-only');
if(params.has('benchmark'))document.querySelectorAll('button,input,select').forEach(e=>e.disabled=true);
const descriptions={layers:'4 ภาพจาก Blender · transform/opacity ผ่าน compositor · motion โดยประมาณและแสงที่ bake แล้ว',sprite:'90 เฟรมจาก Blender · 3 atlases · Canvas 2D ที่ 30 fps · เฟรมเดียวกับวิดีโอ',video:'90 เฟรมชุดเดียวกับ sprite · WebM VP9 + alpha · HTML video · 30 fps',realtime:'Mesh ต้นฉบับจาก Blender · WebGL 4 draw calls · แสงจาก shader แบบง่าย ต่างจาก Eevee'};
let active, mode, playing=false, loop=false, started=0, raf=0, current=1.2, meter=null, generation=0;
const errors=[];
addEventListener('error',e=>errors.push(e.message));
addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
function motion(t){let a=Math.min(1,Math.max(0,t/.4));a=1-(1-a)**3;let b=Math.min(1,Math.max(0,(t-2.4)/.6));b*=b;return[a*(1-b),(1-a)*.22-b*.12];}
function transforms(t,name){const[s,a]=motion(t);const sz=s+(name==='shards'?(1-s)*.45:0);return `rotate(${-a*(name==='ring'?-1:1)}rad) scale(${sz})`;}
function captionFrame(t){const[s]=motion(t);caption.style.opacity=String(s);caption.style.transform=`scale(${.9+.1*s})`;}
async function image(url){const i=new Image();i.src=url;await i.decode();return i;}
async function makeLayers(){const imgs=await Promise.all(groups.map(g=>image(`assets/${g}.png`)));imgs.forEach(i=>visual.append(i));let animations=[];return{draw(t){imgs.forEach((i,n)=>i.style.transform=transforms(t,groups[n]));},play(repeat){animations=imgs.map((i,n)=>i.animate(Array.from({length:91},(_,f)=>({transform:transforms(f/30,groups[n]),offset:f/90,easing:'steps(1,end)'})),{duration:3000,iterations:repeat?Infinity:1,fill:'forwards'}));},stop(){animations.forEach(a=>a.cancel());animations=[];},destroy(){this.stop();}};}
async function makeSprite(){const imgs=await Promise.all([0,1,2].map(n=>image(`assets/atlas-${n}.png`)));const canvas=document.createElement('canvas');canvas.width=640;canvas.height=320;visual.append(canvas);const ctx=canvas.getContext('2d');let last=-1;return{draw(t){const frame=Math.max(0,Math.min(89,Math.floor(t*30)));if(last===frame)return;last=frame;const f=frame%30;ctx.clearRect(0,0,640,320);ctx.drawImage(imgs[Math.floor(frame/30)],f%6*640,Math.floor(f/6)*320,640,320,0,0,640,320);},destroy(){canvas.width=0;imgs.forEach(i=>i.src='');}};}
async function makeVideo(){const v=document.createElement('video');v.muted=true;v.playsInline=true;v.preload='auto';v.src='assets/crest.webm';visual.append(v);await new Promise((ok,no)=>{v.onloadeddata=ok;v.onerror=()=>no(Error('WebM load failed'));});let preview=null;function clearPreview(){if(preview){preview.width=0;preview.remove();preview=null;}}return{video:v,async draw(t){v.pause();const target=Math.max(0,Math.min(2.966,t));if(Math.abs(v.currentTime-target)>.001)await new Promise((ok,no)=>{const timer=setTimeout(()=>no(Error('Video seek timed out')),5000);v.onseeked=()=>{clearTimeout(timer);ok();};v.currentTime=target;});clearPreview();preview=document.createElement('canvas');preview.width=640;preview.height=320;preview.getContext('2d').drawImage(v,0,0);visual.append(preview);},play(repeat){clearPreview();v.loop=repeat;v.currentTime=0;return v.play();},stop(){v.pause();},destroy(){clearPreview();v.pause();v.removeAttribute('src');v.load();}};}
function shader(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
async function makeRealtime(){const data=await fetch('assets/mesh.json').then(r=>r.json());const canvas=document.createElement('canvas');canvas.width=640;canvas.height=320;visual.append(canvas);const gl=canvas.getContext('webgl',{alpha:true,antialias:true,premultipliedAlpha:true,preserveDrawingBuffer:true});if(!gl)throw Error('WebGL unavailable');let disposed=false;canvas.addEventListener('webglcontextlost',()=>{if(!disposed)errors.push('WebGL context lost');});
const vs=shader(gl,gl.VERTEX_SHADER,`attribute vec3 p;attribute vec3 n;attribute vec3 c;uniform float scale;uniform float angle;varying vec3 normal;varying vec3 color;void main(){float a=cos(angle),b=sin(angle);mat3 rot=mat3(a,b,0.,-b,a,0.,0.,0.,1.);vec3 v=rot*p*scale;gl_Position=vec4(v.x/4.25,v.y/2.125,-v.z/10.,1.);normal=rot*n;color=c;}`);
const fs=shader(gl,gl.FRAGMENT_SHADER,`precision mediump float;varying vec3 normal;varying vec3 color;void main(){vec3 n=normalize(normal);float key=max(0.,dot(n,normalize(vec3(-.4,.7,1.))));float fill=max(0.,dot(n,normalize(vec3(.8,.1,1.))));float spec=pow(max(0.,dot(n,normalize(vec3(.3,.4,1.)))),24.);vec3 rgb=color*(.34+.7*key+.28*fill)+vec3(.65,.8,.9)*spec*.45;gl_FragColor=vec4(pow(rgb,vec3(.75)),1.);}`);
const program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.clearColor(0,0,0,0);
const buffers=groups.map(group=>{const floats=[];for(const m of data.meshes.filter(m=>m.group===group)){for(let i=0;i<m.positions.length;i+=3)floats.push(...m.positions.slice(i,i+3),...m.normals.slice(i,i+3),...m.color);}const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(floats),gl.STATIC_DRAW);return{b,count:floats.length/9,group};});
const attrs=['p','n','c'].map(n=>gl.getAttribLocation(program,n));const scale=gl.getUniformLocation(program,'scale'),angle=gl.getUniformLocation(program,'angle');let last=-1;const ext=gl.getExtension('WEBGL_debug_renderer_info');const gpu=ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER);
return{gpu,draw(t){const f=Math.floor(t*30);if(f===last)return;last=f;const[s,a]=motion(f/30);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);for(const item of buffers){gl.bindBuffer(gl.ARRAY_BUFFER,item.b);attrs.forEach((loc,i)=>{gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,36,i*12);});gl.uniform1f(scale,s+(item.group==='shards'?(1-s)*.45:0));gl.uniform1f(angle,a*(item.group==='ring'?-1:1));gl.drawArrays(gl.TRIANGLES,0,item.count);}},destroy(){disposed=true;buffers.forEach(x=>gl.deleteBuffer(x.b));gl.deleteProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);gl.getExtension('WEBGL_lose_context')?.loseContext();canvas.width=0;}};}
function stop(){playing=false;cancelAnimationFrame(raf);active?.stop?.();}
function frame(now){if(!playing)return;if(meter){if(meter.last)meter.intervals.push(now-meter.last);meter.last=now;}let t=Math.max(0,(now-started)/1000);if(t>=3&&!loop){current=2.999;active?.stop?.();if(mode!=='video')active.draw(current);visual.style.visibility='hidden';captionFrame(3);stop();$('#status').textContent='Finished · idle';return;}t%=3;current=t;if(mode==='sprite'||mode==='realtime')active.draw(t);captionFrame(t);if(!params.has('benchmark')){timeInput.value=String(t);$('#timeText').textContent=`${t.toFixed(2)} s`;}raf=requestAnimationFrame(frame);}
async function play(repeat=false){stop();loop=repeat;current=0;visual.style.visibility='visible';await active.draw(0);captionFrame(0);await active.play?.(repeat);started=performance.now();playing=true;raf=requestAnimationFrame(frame);$('#status').textContent=repeat?'Playing · loop':'Playing · one shot';}
async function seek(t){stop();current=t;visual.style.visibility='visible';await active.draw(t);captionFrame(t);timeInput.value=String(t);$('#timeText').textContent=`${t.toFixed(2)} s`;}
async function select(next){const gen=++generation;stop();active?.destroy?.();active=null;visual.replaceChildren();mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===next)));$('#description').textContent=descriptions[next];$('#renderLabel').textContent=next.toUpperCase()+' / 30 FPS SOURCE';const before=performance.now();const result=await({layers:makeLayers,sprite:makeSprite,video:makeVideo,realtime:makeRealtime}[next])();if(gen!==generation){result.destroy?.();return;}active=result;await seek(1.2);$('#status').textContent=`Ready · ${next} · loaded in ${(performance.now()-before).toFixed(0)} ms`;return{mode:next,loadMs:performance.now()-before,gpu:active.gpu??null};}
function measureStart(){meter={last:0,intervals:[],started:performance.now(),videoBefore:active?.video?.getVideoPlaybackQuality?.()??null};}
function measureEnd(){const m=meter;meter=null;const sorted=m.intervals.toSorted((a,b)=>a-b),q=p=>sorted[Math.min(sorted.length-1,Math.floor(sorted.length*p))]??null;const after=active?.video?.getVideoPlaybackQuality?.();return{mode,durationMs:performance.now()-m.started,rafSamples:sorted.length,rafMedianMs:q(.5),rafP95Ms:q(.95),intervalsOver25ms:sorted.filter(x=>x>25).length,intervalsOver50ms:sorted.filter(x=>x>50).length,videoFrames:after?after.totalVideoFrames-(m.videoBefore?.totalVideoFrames??0):null,videoDropped:after?after.droppedVideoFrames-(m.videoBefore?.droppedVideoFrames??0):null,errors:[...errors],visibility:document.visibilityState};}
window.motionLab={select,play,stop,seek,measureStart,measureEnd,info:()=>({mode,playing,current,errors:[...errors],gpu:active?.gpu??null,userAgent:navigator.userAgent,dpr:devicePixelRatio,viewport:[innerWidth,innerHeight]}),background:name=>$('#viewport').className='viewport '+name};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>select(b.dataset.mode));$('#play').onclick=()=>play($('#loop').checked);$('#stop').onclick=()=>{stop();$('#status').textContent='Paused';};timeInput.oninput=()=>seek(Number(timeInput.value));$('#background').onchange=e=>window.motionLab.background(e.target.value);addEventListener('pagehide',()=>{stop();active?.destroy?.();});
window.ready=select(params.get('mode')||'layers');
